Blog App: Add API endpoints
Timbar09/Blogister pull request #11
Opened 2023-07-28 18:23 UTC by Timbar09

In this PR, we ( @Timbar09 and @eudondian ) added API endpoints.

**Changes**
- Created an API endpoint to list all posts for a user.
- Created an API endpoint to list all comments for a user's post.
- Create an API endpoint to add a comment to a post.

2023-07-28 19:12 UTC, Zuhaib042 requested changes
Hi @Timbar09 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![](https://media.giphy.com/media/3o7qDQAFlF8mZjv6fK/giphy.gif)

 ## Highlights
✅ Well done try to add api endpoints

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-28 19:12 UTC, Zuhaib042 commented on config/routes.rb
>      end
- [ ] Kindly consider adding routes for api. right now the routes you have is the normal routes. to add the api endpoints, you need to add the api endpoints.
consider checking this [resource out](https://medium.com/@ryanwaldorf/how-to-add-an-api-to-an-existing-rails-app-1d2419ba91bd)

2023-07-28 19:12 UTC, Zuhaib042 commented on app/controllers/comments_controller.rb
> +  end
- [ ] Kindly consider adding API controllers for your API endpoints. you can take help from this [resource](https://medium.com/@ryanwaldorf/how-to-add-an-api-to-an-existing-rails-app-1d2419ba91bd). I could not get json data from postman from api endpoints.

2023-07-29 15:46 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @Timbar09 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ All linters checks are ok
✅ The correct workflow is used. 
✅ Very descriptive Pull Request(PR)
✅ Your work is well documented.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-29 16:22 UTC, Timbar09 commented
Thank you for the feedback, @bobb-Rob and @Zuhaib042.

2023-07-29 16:22 UTC, merged